name: CI/CD backend-api

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v4

    - name: show source code
      run: ls

    - name : build docker image
      run: docker build -t backend-api .

    - name: show docker images
      run: docker images


  deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: show source code
      run: ls

    - name: deploy docker image
      run: echo "Deploying docker image to server"
 